config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  post 'user/:user_id/secret' => 'user#secret', as: 'user_secret'

  resources :family, only: [:index]
  resources :user, only: [:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/family.rb
class Family < ApplicationRecord
  has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :family
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/family_controller.rb
class FamilyController < ApplicationController
  def index
    @peach_family = User.where(family_id: 1)
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def show
    @gifter = User.find(params[:id])
    @giftee = User.find(@gifter.giftee_id)
  end

  def secret
    password_entered = params[:password]
    @user = User.find(params[:user_id])
    @giftee = User.find(@user.giftee_id)

    if password_entered != @user.password
      @errors = ["You are not #{@user.name}! Wrong password entered."]
      respond_to do |f|
        f.js { render 'wrong_password.js.erb'}
      end
    else
      respond_to do |f|
        f.js { render 'correct_password.js.erb'}
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/family_helper.rb
module FamilyHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/family/index.html.erb
<h1>Welcome, Peach Family!</h1>
<h2>Select your name</h2>
<ul>
  <% @peach_family.each do |peach| %>
    <li><%= link_to(peach.name, user_url(peach.id)) %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecretSanta</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user/correct_password.js.erb
$(".giftee-wrapper").append("YAY, you got <%= @giftee.name %>! Minumum is $30 :) Merry Christmas!")

app/views/user/show.html.erb
<h1><%= @gifter.name %>, enter the secret password sent to your phone to reveal the person you got!</h1>

<%= form_with url: user_secret_url(@gifter.id) do |form| %>
  <%= form.text_field :password %>
  <%= form.submit value: "Submit" %>
<% end %>

<div class="giftee-wrapper">

</div>

app/views/user/wrong_password.js.erb
alert("<%= @errors[0] %>")